In [3]:
from matplotlib import pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd

In [4]:
# Load crime data set into pandas
state_economy = pd.read_csv("state_economy.csv")
state_economy.head()

,SQGDP2 Gross domestic product (GDP) by state 1/,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,(Millions of current dollars),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540

In [5]:
state_economy.columns = state_economy.iloc[3]
state_economy.head()

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
0,(Millions of current dollars),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540

In [6]:
df = state_economy.drop([0,1,2,3])
df

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540
5,0,United States *,2,Private industries,11077820.8,11209860.8,11423916.2,11593875.1,11845005.4,11971058.3,...,16915009,17149802,17434780,17654891,17977475,18189960,18320015,18503089,18724676,18897219
6,0,United States *,3,"Agriculture, forestry, fishing and hunting",130472.2,130667.4,128250.5,123996.9,119576.9,123277.5,...,178485,169133,169305,169446,172100,160510,163799,161084,165741,173393
7,0,United States *,6,"Mining, quarrying, and oil and gas extra...",197013.5,210279.9,232654.1,262763.6,268211,272817.2,...,277806,286628,318582,328770,346432,361288,350091,324570,331738,310758
8,0,United States *,10,Utilities,192325.6,189654.3,200008.3,210583.4,220649.8,226783,...,316793,315226,321076,322592,326273,323103,331440,331778,332671,336272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1447,Legend / Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1448,"1/ For levels: millions of dollars, seasonally...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1449,* For the All industry total and Government an...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1450,(D) Not shown to avoid disclosure of confident...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1451,"Last updated: January 10, 2020-- new statistic...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df1 = df.drop([1447,1448,1449,1450,1451])
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540
5,0,United States *,2,Private industries,11077820.8,11209860.8,11423916.2,11593875.1,11845005.4,11971058.3,...,16915009,17149802,17434780,17654891,17977475,18189960,18320015,18503089,18724676,18897219
6,0,United States *,3,"Agriculture, forestry, fishing and hunting",130472.2,130667.4,128250.5,123996.9,119576.9,123277.5,...,178485,169133,169305,169446,172100,160510,163799,161084,165741,173393
7,0,United States *,6,"Mining, quarrying, and oil and gas extra...",197013.5,210279.9,232654.1,262763.6,268211,272817.2,...,277806,286628,318582,328770,346432,361288,350091,324570,331738,310758
8,0,United States *,10,Utilities,192325.6,189654.3,200008.3,210583.4,220649.8,226783,...,316793,315226,321076,322592,326273,323103,331440,331778,332671,336272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,98000,Far West,70,Health care and social assistance,125571.5,127856.9,129657,131463.7,134938,136238.8,...,246467.3,250742.4,253564.6,258781.8,262129,265730.2,268916.8,274987.1,277646.1,281849.4
1443,98000,Far West,76,"Arts, entertainment, and recreation",31976.3,32997.1,32905.4,34061.6,34142.1,34536.3,...,50302.5,51917.8,52577.5,52251.6,55032.1,55224.1,56127.1,57193.5,57248.4,57232.9
1444,98000,Far West,79,Accommodation and food services,79604.9,80490.5,82115.6,84212.4,85688.8,87335.6,...,137285.7,139258.5,140443.5,143296.6,145704.5,147121.8,150429,152995.3,154373.9,156436.5
1445,98000,Far West,82,Other services (except government and go...,55518.2,55815.6,56405.1,57220.7,58224.7,58973.7,...,73981,76605.5,75965.7,77503.7,78638.8,78846.7,80519.2,81862.6,82476.1,83399.1
1446,98000,Far West,83,Government and government enterprises,304467.5,304652.7,308538.3,311252.2,320793.7,321688.3,...,469320.8,472141.3,478096.4,482490,487239.7,488694.3,499798.8,499748,503338.9,509415.4

In [8]:
df1 = df1.dropna()
df1.head(60)

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540
5,0,United States *,2,Private industries,11077820.8,11209860.8,11423916.2,11593875.1,11845005.4,11971058.3,...,16915009,17149802,17434780,17654891,17977475,18189960,18320015,18503089,18724676,18897219
6,0,United States *,3,"Agriculture, forestry, fishing and hunting",130472.2,130667.4,128250.5,123996.9,119576.9,123277.5,...,178485,169133,169305,169446,172100,160510,163799,161084,165741,173393
7,0,United States *,6,"Mining, quarrying, and oil and gas extra...",197013.5,210279.9,232654.1,262763.6,268211,272817.2,...,277806,286628,318582,328770,346432,361288,350091,324570,331738,310758
8,0,United States *,10,Utilities,192325.6,189654.3,200008.3,210583.4,220649.8,226783,...,316793,315226,321076,322592,326273,323103,331440,331778,332671,336272
9,0,United States *,11,Construction,628497.6,643746,664197.3,670825.2,698776.4,698489.3,...,781456,793586,807546,824254,835302,845371,851643,871387,883874,890334
10,0,United States *,12,Manufacturing,1673020.7,1667801.2,1703061.7,1729883.1,1780270.9,1797640.1,...,2157123,2196235,2251478,2274772,2308125,2337156,2364714,2337619,2355032,2365492
11,0,United States *,13,Durable goods manufacturing,945528.1,946649.2,960430.9,974590.6,1004784.2,1004086.9,...,1217524,1235948,1262095,1272352,1286168,1305727,1321374,1336049,1341656,1344818
12,0,United States *,25,Nondurable goods manufacturing,727492.7,721152.1,742630.8,755292.5,775486.6,793553.2,...,939599,960287,989384,1002420,1021956,1031428,1043341,1001569,1013377,1020675
13,0,United States *,34,Wholesale trade,742767.9,745248.6,759656,772124.5,793711.5,807473.5,...,1157260,1168569,1186549,1184398,1200091,1217788,1246640,1262899,1269028,1287240
14,0,United States *,35,Retail trade,824780.5,834424,846150.7,857951.9,867198.4,868315.4,...,1076822,1088231,1099849,1110781,1130637,1131668,1134430,1153880,1163601,1184561
15,0,United States *,36,Transportation and warehousing,358230.1,368688.6,382488.3,393892,401547.7,409399.7,...,608582,616862,626466,640602,651710,662981,677205,682520,682322,683818
16,0,United States *,45,Information,641864.4,649640.8,638820,639026.4,633845.8,652103.1,...,988552,1007563,1020683,1029258,1071830,1083064,1086825,1097300,1117578,1128766
17,0,United States *,51,Finance and insurance,937845.8,960457.4,988673.7,1007843.5,1031490.8,1025183.3,...,1458466,1492129,1514743,1534582,1567759,1603712,1563231,1603519,1633003,1627360
18,0,United States *,56,Real estate and rental and leasing,1605119.1,1627136.4,1646974.6,1650629,1662555.3,1687356.5,...,2586615,2617475,2649471,2683653,2723444,2751241,2778793,2810419,2852585,2884192
19,0,United States *,60,"Professional, scientific, and technical ...",835694.6,843602.5,857768.7,872539.7,901767.2,909820.7,...,1441165,1461090,1481757,1512817,1542651,1561208,1568966,1608135,1641985,1666927
20,0,United States *,64,Management of companies and enterprises,209399.7,211390.9,216883.1,218775.3,226202.5,229719.9,...,369307,374735,387952,389453,391647,399828,398557,409397,415816,422180
21,0,United States *,65,Administrative and support and waste man...,369891,378262.3,383145.9,388268.5,395494.2,395896.4,...,596463,607404,617962,623097,632879,642126,654439,660429,670080,680985
22,0,United States *,69,Educational services,131123.6,132358.3,134197.7,135236.1,140248.3,142356.6,...,245152,246456,248051,251091,253941,256681,260478,261012,260182,265091
23,0,United States *,70,Health care and social assistance,822064.1,830317.9,843332.1,853338.2,877188.4,889786.5,...,1455219,1468113,1483610,1509432,1528208,1544317,1565675,1590654,1604471,1628029
24,0,United States *,76,"Arts, entertainment, and recreation",118898.2,121125.4,123750.4,125094.1,128828.2,130459.4,...,211715,218795,217244,218380,228752,230808,231747,234546,235130,235527
25,0,United States *,79,Accommodation and food services,352841.5,356439.8,361382,365420,376483.6,379250,...,597773,604697,610567,620094,630546,636823,645283,651561,656663,667387
26,0,United States *,82,Other services (except government and go...,305970.6,308618.9,312521.1,315683.7,320958.5,324930.1,...,410255,416873,421888,427418,435148,440287,446059,450380,453176,458908
27,0,United States *,83,Government and government enterprises,1683518.6,1700160.9,1718957.5,1738442,1758929.6,1778748.8,...,2441640,2461902,2484130,2508266,2532701,2559790,2577789,2595740,2615592,2645324
29,0,United States *,100,"All industry total, overseas activity",78184.2,78863.2,79656.4,80500.5,81409.9,82205,...,113097,113505,114205,115199,116233,117417,118213,119036,119946,121310
30,0,United States *,101,"Government and government enterprises, oversea...",78184.2,78863.2,79656.4,80500.5,81409.9,82205,...,113097,113505,114205,115199,116233,117417,118213,119036,119946,121310
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,34687.5,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4
38,1000,Alabama,13,Durable goods manufacturing,16549.4,16766.9,16949.4,17974.3,18352.2,18441.4,...,22090.5,22503.6,22886.6,23083.9,23249,23670.3,23966.8,24481.9,24589.5,24733.5
39,1000,Alabama,25,Nondurable goods manufacturing,11218.9,10735.6,10853.2,10984.2,11223.5,11517.1,...,12597,13061.4,13604.4,13950.8,13852.4,14279.9,14415.3,13868.6,14028.9,13980.8
40,1000,Alabama,34,Wholesale trade,8747.9,8831.8,8989,9302.1,9346.4,9466.8,...,11944.8,12037.9,12038.1,12107.9,12215,12377.8,12714.5,12817.8,12789.5,12974.8
41,1000,Alabama,35,Retail trade,11560.6,11765.1,11759.7,12142,12282.9,12332.8,...,14074.2,14185.9,14423.9,14796.8,15324.3,15470.4,15596.1,15916.1,16014.8,16341.9
42,1000,Alabama,36,Transportation and warehousing,3928.7,4110.2,4229.4,4387.7,4455.4,4504.6,...,5639.2,5700.2,5821.8,5979.1,6080.9,6191.1,6367,6385.1,6370.4,6385.2
43,1000,Alabama,45,Information,5159,5300.2,5177.5,5111.5,5236.7,5339.2,...,4642.9,4720,4735.1,4594.2,4805.7,4887.4,4857.6,5171.3,5220.3,5280.3
44,1000,Alabama,51,Finance and insurance,9712.1,10116.7,9507.2,9393.2,9094.6,9107.1,...,11783.3,11974,12447.6,12790.9,13382.7,13476.9,13144.3,13422,13693.4,13640.4
45,1000,Alabama,56,Real estate and rental and leasing,13810.9,14080.4,14336.8,14406.3,14406.9,14771.6,...,22365.5,22446.7,22809.8,23100.6,23485.2,23653,23990.4,24212.7,24492.3,24736.8
46,1000,Alabama,60,"Professional, scientific, and technical ...",8022.6,8160.8,8444.8,8446.3,8829.9,8998.5,...,12849.4,13032.6,13428.9,13501.5,13852.4,13951.5,13973.8,14237.8,14582.8,14753.6
47,1000,Alabama,64,Management of companies and enterprises,992.9,1119.3,1184.5,1182.4,1256.2,1191.9,...,2317.5,2068,2198.7,2245.3,2116,2076.7,2154.3,2224.9,2262.6,2284
48,1000,Alabama,65,Administrative and support and waste man...,3409.7,3551.5,3645.3,3774.2,3795,3728.7,...,5616,5751.6,5846.9,5890.3,5958.4,6064.1,6270.3,6340.8,6440.7,6592.8
49,1000,Alabama,69,Educational services,758.8,771,761.2,785.5,799.5,827.9,...,1323,1319.3,1313.1,1296.1,1346.1,1328.2,1391.3,1382.3,1371.5,1391.5
50,1000,Alabama,70,Health care and social assistance,9731.1,9801.4,9925.1,10140,10347.9,10535.2,...,15572.8,15747,15847,16043.6,16312.6,16422.7,16586.5,16935.9,17073.6,17347.3
51,1000,Alabama,76,"Arts, entertainment, and recreation",533,519.7,523,534.4,546.9,554.6,...,779.6,796,817.1,815.4,863.1,862.3,866.1,908.8,906,902.1
52,1000,Alabama,79,Accommodation and food services,3453,3480.4,3503,3600.1,3711.7,3722.7,...,5940.6,6032.5,6070.2,6181.5,6341.5,6411,6588.8,6606.2,6651,6777.5
53,1000,Alabama,82,Other services (except government and go...,4228.1,4251.9,4322.2,4340.8,4446.8,4483.2,...,5220.7,5323.1,5395.7,5494.6,5622.4,5707,5830.4,5858,5894.3,5987.1
54,1000,Alabama,83,Government and government enterprises,24721.5,24974.7,25156.2,25519.8,25466.9,26225.9,...,35457.6,35263.7,35847,36159.5,36463,36644.7,36972.1,37102.5,37367.3,37835.8
55,2000,Alaska,1,All industry total,37377.7,38626,40251.7,42843.8,42633.9,44349.8,...,51274,52060.2,52778.4,53563,54372.7,55410,55590.6,54941.4,55494.6,55429.6
56,2000,Alaska,2,Private industries,29922.1,31124.5,32738.4,35105.6,34926.8,36498.5,...,40781.9,41567.9,42087.3,42878.5,43551.9,44497.8,44702.2,43966.2,44448.1,44281.3
57,2000,Alaska,3,"Agriculture, forestry, fishing and hunting",216.5,261.2,376.2,526.8,404.9,348.8,...,374.7,399.4,404.1,356.3,367.1,442.8,459.9,449.5,432.4,439.3
58,2000,Alaska,6,"Mining, quarrying, and oil and gas extra...",8610.3,9655,10508,12822.4,12675.7,13867.9,...,8335.7,8624.2,8926,9291.4,9150.9,9472.7,9293.3,8697.5,8910.4,8423.5
59,2000,Alaska,10,Utilities,431.2,434.4,448.1,476.5,488.7,512.5,...,774.8,779.1,791.9,812.5,812.9,805.7,821.8,806,799.5,811.9
60,2000,Alaska,11,Construction,1979.2,2055,2093.2,2026.5,2052.4,2061.2,...,1843.7,1842.5,1820.5,1883.4,1906.4,1985.2,2101.4,2072.2,2036.9,2029.3
61,2000,Alaska,12,Manufacturing,1278.4,1181.7,1291.2,1309.8,1377.1,1414,...,1521.3,1724.1,1745.6,1813.7,1831.9,1855.6,1869.3,1768.1,1809.4,1837.5
62,2000,Alaska,13,Durable goods manufacturing,156.7,159.4,157,152.4,160.9,160.2,...,229,232.4,240.5,233.1,232.9,233.2,234.3,245.5,244.2,248.3
63,2000,Alaska,25,Nondurable goods manufacturing,1121.7,1022.3,1134.2,1157.4,1216.2,1253.8,...,1292.2,1491.7,1505.1,1580.6,1599.1,1622.4,1635,1522.7,1565.2,1589.2
64,2000,Alaska,34,Wholesale trade,869.5,861.1,924.8,893.9,934,963.2,...,1281.7,1294.3,1316.7,1334.9,1358.6,1398.7,1452.1,1445.8,1453,1491.5

In [9]:
df1['GeoName'].value_counts()

United States *         26
Kentucky                24
California              24
Alabama                 24
Georgia                 24
New England             24
Plains                  24
Connecticut             24
Virginia                24
Michigan                24
Rocky Mountain          24
Mississippi             24
Louisiana               24
Delaware                24
North Dakota            24
Missouri                24
Nebraska                24
Kansas                  24
Massachusetts           24
South Carolina          24
Oregon                  24
Texas                   24
New York                24
Montana                 24
New Hampshire           24
Far West                24
South Dakota            24
Hawaii                  24
New Jersey              24
New Mexico              24
Rhode Island            24
Vermont                 24
Maine                   24
Minnesota               24
Wyoming                 24
District of Columbia    24
Pennsylvania            24
Oklahoma                24
Alaska                  24
Ohio                    24
Mideast                 24
West Virginia           24
Idaho                   24
North Carolina          24
Washington              24
Maryland                24
Arkansas                24
Wisconsin               24
Great Lakes             24
Tennessee               24
Southeast               24
Arizona                 24
Iowa                    24
Southwest               24
Florida                 24
Colorado                24
Illinois                24
Utah                    24
Indiana                 24
Nevada                  24
Name: GeoName, dtype: int64

In [10]:
df1 = df1[df1.GeoName != 'United States *']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,98000,Far West,70,Health care and social assistance,125571.5,127856.9,129657,131463.7,134938,136238.8,...,246467.3,250742.4,253564.6,258781.8,262129,265730.2,268916.8,274987.1,277646.1,281849.4
1443,98000,Far West,76,"Arts, entertainment, and recreation",31976.3,32997.1,32905.4,34061.6,34142.1,34536.3,...,50302.5,51917.8,52577.5,52251.6,55032.1,55224.1,56127.1,57193.5,57248.4,57232.9
1444,98000,Far West,79,Accommodation and food services,79604.9,80490.5,82115.6,84212.4,85688.8,87335.6,...,137285.7,139258.5,140443.5,143296.6,145704.5,147121.8,150429,152995.3,154373.9,156436.5
1445,98000,Far West,82,Other services (except government and go...,55518.2,55815.6,56405.1,57220.7,58224.7,58973.7,...,73981,76605.5,75965.7,77503.7,78638.8,78846.7,80519.2,81862.6,82476.1,83399.1
1446,98000,Far West,83,Government and government enterprises,304467.5,304652.7,308538.3,311252.2,320793.7,321688.3,...,469320.8,472141.3,478096.4,482490,487239.7,488694.3,499798.8,499748,503338.9,509415.4

In [11]:
df1 = df1[df1.GeoName != 'Far West']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1418,97000,Rocky Mountain,70,Health care and social assistance,22645,23106.6,23404.4,23547.9,24453,24619.7,...,44064.8,45389.2,45310.3,46483.6,46730.8,47345,47999.3,48769.5,49148.3,49959.9
1419,97000,Rocky Mountain,76,"Arts, entertainment, and recreation",3700.5,3730.3,3837.3,4010.7,4193.9,4037.1,...,8587.7,9035.5,9038.5,8990.9,9540,9541.3,9473.6,9569.5,9538,9518.3
1420,97000,Rocky Mountain,79,Accommodation and food services,12100.9,12128.3,12265.4,12539.6,13135.7,13163.9,...,21665.1,21950.7,22232.3,22619.7,23122,23302.3,23705.3,23921,24022,24403.8
1421,97000,Rocky Mountain,82,Other services (except government and go...,10347.8,10431.8,10527.9,10645.4,10885.2,11002.3,...,15398.4,15614.5,15833.5,15987.6,16324.3,16518,16823.3,16912.3,17047.1,17267.3
1422,97000,Rocky Mountain,83,Government and government enterprises,57053.7,57369.1,57531.5,58531.6,59063.6,59723.3,...,85772.6,86679.4,87987.5,88193.6,89550.3,90328,91040,92441.6,93506.4,94627.6

In [12]:
df1 = df1[df1.GeoName != 'Rocky Mountain']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1394,96000,Southwest,70,Health care and social assistance,78588,79076.4,81096.9,82434.4,84492.6,86359.3,...,154677.8,154859.2,156320.4,159044.1,160975.7,162637.7,165443.8,167616.6,169370.3,171996.6
1395,96000,Southwest,76,"Arts, entertainment, and recreation",7511.9,7747.4,8266.3,8255.7,8322.5,8652,...,17307.2,18103.1,17731.7,17512.6,18793.2,18977.3,18837.4,19273.7,19387.6,19431.4
1396,96000,Southwest,79,Accommodation and food services,39534.7,40046.8,40628.7,41525.8,44232.3,44312.5,...,69148,69902.3,70915.9,72149.7,73712.5,74636.3,75570.3,76099.3,76632.1,78004.7
1397,96000,Southwest,82,Other services (except government and go...,30592.9,30864.8,31370.5,31831,32967.6,33444.7,...,45463.5,46254.9,47405,47964.1,49293.4,49701.2,50560.3,50982.3,51446.2,52360.7
1398,96000,Southwest,83,Government and government enterprises,174626.7,175922.5,177461.2,180821.3,183244.8,185404.5,...,273075.7,275821,278711.8,279264.5,282591.2,286595.5,288286.5,292033.1,294105.2,297397.7

In [13]:
df1 = df1[df1.GeoName != 'Southwest']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1370,95000,Southeast,70,Health care and social assistance,179690.9,181343.9,183804.5,184936.2,191135.3,193844.2,...,318604.1,320166.7,324014.3,329015.3,333238.2,336198.2,340981.6,346136.2,349268.5,354654.7
1371,95000,Southeast,76,"Arts, entertainment, and recreation",24578.4,24837,25645.6,25309.2,26805.5,26900.8,...,41125.8,42847.3,42254.4,42147.3,44095.1,44679.5,45014.5,45272.1,45156.9,45287
1372,95000,Southeast,79,Accommodation and food services,86174.8,86340.2,87335.8,87779.6,90488.8,91026.2,...,141538.5,142518.7,144777,146663.3,148664.9,150800,152403.2,153886.5,155297.2,157655.8
1373,95000,Southeast,82,Other services (except government and go...,70499.1,71324.4,72221.6,72687.1,74570.8,75388.6,...,94160.7,95274.8,96752,97889.3,99616.8,101409.8,102509.7,103958.5,104555.1,106015.4
1374,95000,Southeast,83,Government and government enterprises,386155.6,389745.3,392831.6,397004.1,400782.4,405008,...,550016,556094.9,561585.3,564185.6,568927.7,575917,576988.3,582678,587013,593582.9

In [14]:
df1 = df1[df1.GeoName != 'Southeast']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1346,94000,Plains,70,Health care and social assistance,59228.6,59878.8,61093.7,61698.1,63095,63892,...,103633.6,103844.2,105173.2,106984.9,108592.1,109665.3,111217,111890.9,112652.6,114110.3
1347,94000,Plains,76,"Arts, entertainment, and recreation",6278,6513.3,6490.9,6719.4,6778.9,7099.7,...,10050.6,10402,10062.3,10347,10836.8,10879.5,10870,11034.4,10973.9,11022.6
1348,94000,Plains,79,Accommodation and food services,19616.1,19703.4,19993.9,19959.6,20589.6,20493.7,...,31243.3,31670,31737.7,32193.8,32560.6,32876.2,33181.4,32922.6,33190.1,33763.6
1349,94000,Plains,82,Other services (except government and go...,20361.9,20391.9,20657,20741.1,20968.2,21161.5,...,26187.4,26322.9,26674.1,27001.4,27437.1,27712.6,27975,28062.6,28304.4,28667.4
1350,94000,Plains,83,Government and government enterprises,96911.8,97581,98822.4,100343.8,101956.2,103355.8,...,139905.5,140464.4,142375.7,142936.2,144631.8,146554.8,146339.4,147747.5,149026.1,150701.2

In [15]:
df1 = df1[df1.GeoName != 'Plains']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1322,93000,Great Lakes,70,Health care and social assistance,133849,135709.4,137792,139361.4,143104.6,145372.4,...,216833.1,218718.1,220267,223702.3,226010.4,228563.4,231294.2,234522.5,236017.6,239110
1323,93000,Great Lakes,76,"Arts, entertainment, and recreation",16988.3,17108.6,17754.1,18187.8,17879.9,18091.6,...,26379,26938.6,26466.5,27173.3,28219,28564,28471.6,28807,28790.4,28795.1
1324,93000,Great Lakes,79,Accommodation and food services,42167.7,42660,43020.4,43022.8,44667.3,44597.1,...,72277.4,73133,73517.1,74784.2,75672.3,76633,77112.2,77665.5,78418.1,79685.2
1325,93000,Great Lakes,82,Other services (except government and go...,45778.7,46170.5,46866.7,47128.9,47419.3,47920.3,...,57982.7,58545.5,59587,60110.9,61230.2,61826.2,62463.1,62623.8,62956.8,63625.1
1326,93000,Great Lakes,83,Government and government enterprises,206412.4,209652.6,211025.8,212814.2,216678.8,219338.4,...,270649.5,274903.7,274933.9,277343.2,278794.1,282629.5,283392.9,285681.5,287655.4,291450.3

In [16]:
df1 = df1[df1.GeoName != 'Great Lakes']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1298,92000,Mideast,70,Health care and social assistance,165784.9,166480.2,169054.1,171368.5,175572.9,178287.6,...,274739.8,276664.8,281052.6,286872.5,291034.1,293995.1,298601.3,303148.7,305938.7,310469.5
1299,92000,Mideast,76,"Arts, entertainment, and recreation",21170.8,21541.2,22012.2,21702.1,24045.3,24311.3,...,46359.5,47742.7,47385,47950.3,49636,50259.3,50140.3,50700.9,51264.3,51383.1
1300,92000,Mideast,79,Accommodation and food services,55339.5,56534.6,57276.7,57607.2,58697.2,59362.6,...,92976.9,94271.6,94644.5,95800.2,97826.3,97841.3,98928.9,99420.9,99794.1,101923.9
1301,92000,Mideast,82,Other services (except government and go...,56819.7,57387.8,58081.3,58879.5,59207.8,60129.1,...,77119.7,77939.5,79154.3,80075.7,81317.8,82682.8,83358.3,83872.3,84160.4,85059
1302,92000,Mideast,83,Government and government enterprises,300639.4,305669.5,311354.3,314237.5,311620.1,317694.8,...,429879.9,432136.1,434816.1,446687.6,451476.8,456874.3,459055.1,460796.4,464747.8,469315

In [17]:
df1 = df1[df1.GeoName != 'Mideast']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1274,91000,New England,70,Health care and social assistance,56705.9,56865.3,57429.2,58527.9,60397.1,61172.9,...,96199.5,97729.1,97907.7,98546.5,99495.9,100179.8,101218.4,103582.6,104428.9,105878.5
1275,91000,New England,76,"Arts, entertainment, and recreation",6694.4,6650.7,6839,6848,6660.2,6830.6,...,11602,11807.8,11728.7,12008.4,12601.9,12685.6,12815.3,12695,12770.5,12856.6
1276,91000,New England,79,Accommodation and food services,18302.5,18535.7,18745,18772.6,18983.9,18958.5,...,31637.2,31991.3,32297.9,32585.2,33281.5,33610.5,33951,34649.9,34935.6,35513.6
1277,91000,New England,82,Other services (except government and go...,16052.5,16232.3,16391.1,16550.2,16715,16909.9,...,19961.9,20315.7,20516.8,20885.4,21289.6,21589.7,21850.1,22105.6,22229.8,22513.9
1278,91000,New England,83,Government and government enterprises,79065,80705.4,81735.2,82935.6,83378.1,84329.6,...,109923.7,110156,111418.2,111966.2,113256.3,114779.7,114675.2,115577.9,116253.2,117523.9

In [18]:
df1 = df1[df1.GeoName != 'New England']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1646.4,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,272.3,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1355.6,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,578,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6207.6,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7

In [19]:
df1['GeoName'].value_counts()

Kentucky                24
Iowa                    24
Delaware                24
North Dakota            24
Missouri                24
Alaska                  24
Kansas                  24
Massachusetts           24
Washington              24
Oklahoma                24
Arizona                 24
South Carolina          24
Oregon                  24
Louisiana               24
Texas                   24
New York                24
Montana                 24
New Hampshire           24
Florida                 24
South Dakota            24
Hawaii                  24
Colorado                24
Illinois                24
New Jersey              24
Wisconsin               24
Maryland                24
California              24
Alabama                 24
Arkansas                24
Minnesota               24
Wyoming                 24
Utah                    24
District of Columbia    24
Rhode Island            24
Tennessee               24
Pennsylvania            24
New Mexico              24
Indiana                 24
Georgia                 24
Mississippi             24
Ohio                    24
West Virginia           24
Idaho                   24
North Carolina          24
Connecticut             24
Vermont                 24
Virginia                24
Nebraska                24
Maine                   24
Michigan                24
Nevada                  24
Name: GeoName, dtype: int64

In [20]:
df1['GeoName'].nunique()

51

In [21]:
df1 = df1[df1.LineCode != '1']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1646.4,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,272.3,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1355.6,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,578,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6207.6,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7

In [22]:
df1 = df1[df1.LineCode != '2']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,34687.5,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1646.4,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,272.3,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1355.6,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,578,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6207.6,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7

In [23]:
df1 = df1[df1.LineCode != '13']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,34687.5,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1646.4,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,272.3,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1355.6,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,578,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6207.6,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7

In [24]:
df1 = df1[df1.LineCode != '25']
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,34687.5,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1646.4,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,272.3,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1355.6,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,578,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6207.6,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7

In [33]:
df1 = pd.DataFrame(df1)
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,col3
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6,2659.82643.42600.62617.7
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4,2421.42645.82783.33137.7
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6,3586.637304008.83970.7
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5,7434.97605.67750.88116.4
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4,27768.327502.527802.528958.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1680.1,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8,1007.5996.11004.91041.3
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,281.6,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1,131.8145.2152.4155.7
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1380.5,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1,833.2802.2798.3824
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,592.9,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7,455.2448.6464.3478.2
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6203.9,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7,3779.63735.237673865.6

In [44]:
df1['2005:Q1'] = df1['2005:Q1'].astype(float)

ValueError: could not convert string to float: '(D)'

In [37]:
sum_column = df1["2005:Q1"] + df1["2005:Q2"] + df1["2005:Q3"] + df1["2005:Q4"]
df1["2005"] = sum_column
df1

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3,col3,2005
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6,2659.82643.42600.62617.7,2659.82643.42600.62617.7
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4,2421.42645.82783.33137.7,2421.42645.82783.33137.7
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6,3586.637304008.83970.7,3586.637304008.83970.7
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5,7434.97605.67750.88116.4,7434.97605.67750.88116.4
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4,27768.327502.527802.528958.5,27768.327502.527802.528958.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1250,56000,Wyoming,70,Health care and social assistance,1007.5,996.1,1004.9,1041.3,1060.5,1077.9,...,1673.4,1739.5,1736.8,1752.2,1763.3,1776.2,1781.3,1797.8,1007.5996.11004.91041.3,1007.5996.11004.91041.3
1251,56000,Wyoming,76,"Arts, entertainment, and recreation",131.8,145.2,152.4,155.7,175.9,162.2,...,274.3,276.3,289.3,293.5,290.5,282.7,278.2,284.1,131.8145.2152.4155.7,131.8145.2152.4155.7
1252,56000,Wyoming,79,Accommodation and food services,833.2,802.2,798.3,824,927.6,931.4,...,1388.7,1428,1448.2,1468.3,1484.7,1534.5,1546.7,1585.1,833.2802.2798.3824,833.2802.2798.3824
1253,56000,Wyoming,82,Other services (except government and go...,455.2,448.6,464.3,478.2,524.9,547.9,...,600.1,614.4,619.4,624.6,643.6,643.9,652.7,665.7,455.2448.6464.3478.2,455.2448.6464.3478.2
1254,56000,Wyoming,83,Government and government enterprises,3779.6,3735.2,3767,3865.6,3895.1,3966.5,...,6233.8,6194.5,6276.9,6366.3,6334.3,6413.3,6469,6548.7,3779.63735.237673865.6,3779.63735.237673865.6