In [11]:
import csv
import pandas as pd

In [12]:
file = 'state_economy.csv'

In [13]:
base_econ = pd.read_csv(file)

In [14]:
base_econ.head(10)

,SQGDP2 Gross domestic product (GDP) by state 1/,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,(Millions of current dollars),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540
5,0,United States *,2,Private industries,11077820.8,11209860.8,11423916.2,11593875.1,11845005.4,11971058.3,...,16915009,17149802,17434780,17654891,17977475,18189960,18320015,18503089,18724676,18897219
6,0,United States *,3,"Agriculture, forestry, fishing and hunting",130472.2,130667.4,128250.5,123996.9,119576.9,123277.5,...,178485,169133,169305,169446,172100,160510,163799,161084,165741,173393
7,0,United States *,6,"Mining, quarrying, and oil and gas extra...",197013.5,210279.9,232654.1,262763.6,268211,272817.2,...,277806,286628,318582,328770,346432,361288,350091,324570,331738,310758
8,0,United States *,10,Utilities,192325.6,189654.3,200008.3,210583.4,220649.8,226783,...,316793,315226,321076,322592,326273,323103,331440,331778,332671,336272
9,0,United States *,11,Construction,628497.6,643746,664197.3,670825.2,698776.4,698489.3,...,781456,793586,807546,824254,835302,845371,851643,871387,883874,890334

In [20]:
base_econ.columns = base_econ.iloc[3]

In [16]:
base_econ.head(50)

3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
0,(Millions of current dollars),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Bureau of Economic Analysis,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,State or DC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,GeoFips,GeoName,LineCode,Description,2005:Q1,2005:Q2,2005:Q3,2005:Q4,2006:Q1,2006:Q2,...,2017:Q2,2017:Q3,2017:Q4,2018:Q1,2018:Q2,2018:Q3,2018:Q4,2019:Q1,2019:Q2,2019:Q3
4,0,United States *,1,All industry total,12761337,12910022,13142873,13332316,13603933,13749806,...,19356649,19611704,19918910,20163159,20510177,20749752,20897804,21098827,21340267,21542540
5,0,United States *,2,Private industries,11077820.8,11209860.8,11423916.2,11593875.1,11845005.4,11971058.3,...,16915009,17149802,17434780,17654891,17977475,18189960,18320015,18503089,18724676,18897219
6,0,United States *,3,"Agriculture, forestry, fishing and hunting",130472.2,130667.4,128250.5,123996.9,119576.9,123277.5,...,178485,169133,169305,169446,172100,160510,163799,161084,165741,173393
7,0,United States *,6,"Mining, quarrying, and oil and gas extra...",197013.5,210279.9,232654.1,262763.6,268211,272817.2,...,277806,286628,318582,328770,346432,361288,350091,324570,331738,310758
8,0,United States *,10,Utilities,192325.6,189654.3,200008.3,210583.4,220649.8,226783,...,316793,315226,321076,322592,326273,323103,331440,331778,332671,336272
9,0,United States *,11,Construction,628497.6,643746,664197.3,670825.2,698776.4,698489.3,...,781456,793586,807546,824254,835302,845371,851643,871387,883874,890334
10,0,United States *,12,Manufacturing,1673020.7,1667801.2,1703061.7,1729883.1,1780270.9,1797640.1,...,2157123,2196235,2251478,2274772,2308125,2337156,2364714,2337619,2355032,2365492
11,0,United States *,13,Durable goods manufacturing,945528.1,946649.2,960430.9,974590.6,1004784.2,1004086.9,...,1217524,1235948,1262095,1272352,1286168,1305727,1321374,1336049,1341656,1344818
12,0,United States *,25,Nondurable goods manufacturing,727492.7,721152.1,742630.8,755292.5,775486.6,793553.2,...,939599,960287,989384,1002420,1021956,1031428,1043341,1001569,1013377,1020675
13,0,United States *,34,Wholesale trade,742767.9,745248.6,759656,772124.5,793711.5,807473.5,...,1157260,1168569,1186549,1184398,1200091,1217788,1246640,1262899,1269028,1287240
14,0,United States *,35,Retail trade,824780.5,834424,846150.7,857951.9,867198.4,868315.4,...,1076822,1088231,1099849,1110781,1130637,1131668,1134430,1153880,1163601,1184561
15,0,United States *,36,Transportation and warehousing,358230.1,368688.6,382488.3,393892,401547.7,409399.7,...,608582,616862,626466,640602,651710,662981,677205,682520,682322,683818
16,0,United States *,45,Information,641864.4,649640.8,638820,639026.4,633845.8,652103.1,...,988552,1007563,1020683,1029258,1071830,1083064,1086825,1097300,1117578,1128766
17,0,United States *,51,Finance and insurance,937845.8,960457.4,988673.7,1007843.5,1031490.8,1025183.3,...,1458466,1492129,1514743,1534582,1567759,1603712,1563231,1603519,1633003,1627360
18,0,United States *,56,Real estate and rental and leasing,1605119.1,1627136.4,1646974.6,1650629,1662555.3,1687356.5,...,2586615,2617475,2649471,2683653,2723444,2751241,2778793,2810419,2852585,2884192
19,0,United States *,60,"Professional, scientific, and technical ...",835694.6,843602.5,857768.7,872539.7,901767.2,909820.7,...,1441165,1461090,1481757,1512817,1542651,1561208,1568966,1608135,1641985,1666927
20,0,United States *,64,Management of companies and enterprises,209399.7,211390.9,216883.1,218775.3,226202.5,229719.9,...,369307,374735,387952,389453,391647,399828,398557,409397,415816,422180
21,0,United States *,65,Administrative and support and waste man...,369891,378262.3,383145.9,388268.5,395494.2,395896.4,...,596463,607404,617962,623097,632879,642126,654439,660429,670080,680985
22,0,United States *,69,Educational services,131123.6,132358.3,134197.7,135236.1,140248.3,142356.6,...,245152,246456,248051,251091,253941,256681,260478,261012,260182,265091
23,0,United States *,70,Health care and social assistance,822064.1,830317.9,843332.1,853338.2,877188.4,889786.5,...,1455219,1468113,1483610,1509432,1528208,1544317,1565675,1590654,1604471,1628029
24,0,United States *,76,"Arts, entertainment, and recreation",118898.2,121125.4,123750.4,125094.1,128828.2,130459.4,...,211715,218795,217244,218380,228752,230808,231747,234546,235130,235527
25,0,United States *,79,Accommodation and food services,352841.5,356439.8,361382,365420,376483.6,379250,...,597773,604697,610567,620094,630546,636823,645283,651561,656663,667387
26,0,United States *,82,Other services (except government and go...,305970.6,308618.9,312521.1,315683.7,320958.5,324930.1,...,410255,416873,421888,427418,435148,440287,446059,450380,453176,458908
27,0,United States *,83,Government and government enterprises,1683518.6,1700160.9,1718957.5,1738442,1758929.6,1778748.8,...,2441640,2461902,2484130,2508266,2532701,2559790,2577789,2595740,2615592,2645324
28,0,United States *,NaN,Addenda:,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,0,United States *,100,"All industry total, overseas activity",78184.2,78863.2,79656.4,80500.5,81409.9,82205,...,113097,113505,114205,115199,116233,117417,118213,119036,119946,121310
30,0,United States *,101,"Government and government enterprises, oversea...",78184.2,78863.2,79656.4,80500.5,81409.9,82205,...,113097,113505,114205,115199,116233,117417,118213,119036,119946,121310
31,1000,Alabama,1,All industry total,152640.8,154962.5,156410.9,159867.4,161258.9,163487,...,208359.9,210680.7,214779.5,217369.7,220572.2,223140.7,225859.4,227735,229939.2,232144.7
32,1000,Alabama,2,Private industries,127919.3,129987.8,131254.7,134347.6,135791.9,137261.1,...,172902.2,175417,178932.5,181210.2,184109.2,186496.1,188887.2,190632.5,192571.8,194308.9
33,1000,Alabama,3,"Agriculture, forestry, fishing and hunting",2659.8,2643.4,2600.6,2617.7,1968.9,2090.1,...,2392.5,2202,2232.9,2359.5,2380,2117.7,2243.8,1878.1,1942.7,2029.6
34,1000,Alabama,6,"Mining, quarrying, and oil and gas extra...",2421.4,2645.8,2783.3,3137.7,2939.1,2841.3,...,2758.9,2804.8,3129.6,3056.7,2964.5,3032.7,2975.3,2679.9,2755.2,2581.4
35,1000,Alabama,10,Utilities,3586.6,3730,4008.8,3970.7,4397.9,4284,...,5791.5,6367,6507.8,6357.9,6213.4,6554,6837.1,7057.4,7071.8,7155.6
36,1000,Alabama,11,Construction,7434.9,7605.6,7750.8,8116.4,8353.5,8522.5,...,7202.2,7343.4,7377.4,7563.8,7743.6,7961.2,8117.7,8246.8,8420.5,8432.5
37,1000,Alabama,12,Manufacturing,27768.3,27502.5,27802.5,28958.5,29575.7,29958.5,...,34687.5,35565,36491.1,37034.7,37101.5,37950.3,38382.1,38350.4,38618.4,38714.4
38,1000,Alabama,13,Durable goods manufacturing,16549.4,16766.9,16949.4,17974.3,18352.2,18441.4,...,22090.5,22503.6,22886.6,23083.9,23249,23670.3,23966.8,24481.9,24589.5,24733.5
39,1000,Alabama,25,Nondurable goods manufacturing,11218.9,10735.6,10853.2,10984.2,11223.5,11517.1,...,12597,13061.4,13604.4,13950.8,13852.4,14279.9,14415.3,13868.6,14028.9,13980.8
40,1000,Alabama,34,Wholesale trade,8747.9,8831.8,8989,9302.1,9346.4,9466.8,...,11944.8,12037.9,12038.1,12107.9,12215,12377.8,12714.5,12817.8,12789.5,12974.8
41,1000,Alabama,35,Retail trade,11560.6,11765.1,11759.7,12142,12282.9,12332.8,...,14074.2,14185.9,14423.9,14796.8,15324.3,15470.4,15596.1,15916.1,16014.8,16341.9
42,1000,Alabama,36,Transportation and warehousing,3928.7,4110.2,4229.4,4387.7,4455.4,4504.6,...,5639.2,5700.2,5821.8,5979.1,6080.9,6191.1,6367,6385.1,6370.4,6385.2
43,1000,Alabama,45,Information,5159,5300.2,5177.5,5111.5,5236.7,5339.2,...,4642.9,4720,4735.1,4594.2,4805.7,4887.4,4857.6,5171.3,5220.3,5280.3
44,1000,Alabama,51,Finance and insurance,9712.1,10116.7,9507.2,9393.2,9094.6,9107.1,...,11783.3,11974,12447.6,12790.9,13382.7,13476.9,13144.3,13422,13693.4,13640.4
45,1000,Alabama,56,Real estate and rental and leasing,13810.9,14080.4,14336.8,14406.3,14406.9,14771.6,...,22365.5,22446.7,22809.8,23100.6,23485.2,23653,23990.4,24212.7,24492.3,24736.8
46,1000,Alabama,60,"Professional, scientific, and technical ...",8022.6,8160.8,8444.8,8446.3,8829.9,8998.5,...,12849.4,13032.6,13428.9,13501.5,13852.4,13951.5,13973.8,14237.8,14582.8,14753.6
47,1000,Alabama,64,Management of companies and enterprises,992.9,1119.3,1184.5,1182.4,1256.2,1191.9,...,2317.5,2068,2198.7,2245.3,2116,2076.7,2154.3,2224.9,2262.6,2284
48,1000,Alabama,65,Administrative and support and waste man...,3409.7,3551.5,3645.3,3774.2,3795,3728.7,...,5616,5751.6,5846.9,5890.3,5958.4,6064.1,6270.3,6340.8,6440.7,6592.8
49,1000,Alabama,69,Educational services,758.8,771,761.2,785.5,799.5,827.9,...,1323,1319.3,1313.1,1296.1,1346.1,1328.2,1391.3,1382.3,1371.5,1391.5

In [25]:
base_econ = base_econ.iloc(base_econ[[4:]])

SyntaxError: invalid syntax (<ipython-input-25-26e8b68348cc>, line 1)

In [ ]:
base_econ